### ISSUE TITLE
Use of multiple databases

### ISSUE THREAD

**Issue by aberman** [ostinelli/pgpool#2]
I am wondering why there is a database configuration along with the pools config.  When using poolboy, you can easily configure multiple databases by configuring two different pools:

``` Erlang
{pools, [
            {pool1, [
                {size, 10},
                {max_overflow, 20}
            ], [
                {hostname, "127.0.0.1"},
                {database, "db1"},
                {username, "db1"},
                {password, "abc123"}
            ]},
            {pool2, [
                {size, 5},
                {max_overflow, 10}
            ], [
                {hostname, "127.0.0.1"},
                {database, "db2"},
                {username, "db2"},
                {password, "abc123"}
            ]}
        ]}
```

Just seems a lot simpler to me unless there was some rationale you had for doing it the way you did.

**Comment by ostinelli** [comment]
This could be have been done too. A couple of reasons why this was done differently.

1 - I would miss from your proposal is the fact that I'd still want the `databases` environment wrapper, so that additional configuration variables can be added if needed. For instance:

``` erlang
{pgpool, [
  {databases, [
    ...
  ]},
  {other_variable, other_value} 
]}
```

2 - My intention was to clearly differentiate the _pool_ params from _connection_ the params. If you use database names, your example becomes:

``` erlang
{pgpool, [
    {db1_name, [
        {size, 10},
        {max_overflow, 20}
    ], [
        {hostname, "127.0.0.1"},
        {database, "db1"},
        {username, "db1"},
        {password, "abc123"}
    ]},
    {db2_name, [
        {size, 5},
        {max_overflow, 10}
    ], [
        {hostname, "127.0.0.1"},
        {database, "db2"},
        {username, "db2"},
        {password, "abc123"}
    ]}
]}
```

It is not immediate what `size` refers to, while in the current config you can see that it's a property of the `pool` key:

``` erlang
{pgpool, [
  {databases, [
    {db1_name, [
      {pool, [
        {size, 10}
      ]},
      {connection, [
        {host, "localhost"},
        {user, "postgres"},
        {pass, ""},
        {options, [
          {port, 5432},
          {ssl, false},
          {database, "db1"}
        ]}
      ]}
    ]}
  ]}
]}
```

3 - In the current way, the params just get transferred to the related libraries (poolboy & epgsql) and no additional processing is needed.

Hope this clears up.
